
services:

  cheshire-cat-core:
    build:
      context: ./core
    container_name: cheshire_cat_core
    # Uncomment the two lines below to use your .env (see .env.example)
    # env_file:
    #  - .env
    depends_on:
      - cheshire-cat-vector-memory
      - ollama
    ports:
      - ${CCAT_CORE_PORT:-1865}:80
      - 5678:5678 # only for development purposes (take away in production)
    extra_hosts:
      - "host.docker.internal:host-gateway" # This add an entry to /etc/hosts file in the container mapping host.docker.internal to the host machine IP addr, allowing the container to access services running on the host, not only on Win and Mac but also Linux. See https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host and https://docs.docker.com/reference/cli/docker/container/run/#add-host
    environment:
      # Timezone
      - TZ=${CCAT_TIMEZONE:-UTC}
    volumes:
      - ./core:/app
    command:
      - python
      - "-m"
      - "cat.main"
    restart: unless-stopped
 
  cheshire-cat-vector-memory:
    image: qdrant/qdrant:latest
    container_name: cheshire_cat_vector_memory
    expose:
      - 6333
    volumes:
      - ./cat/long_term_memory/vector:/qdrant/storage
    restart: unless-stopped

  ollama:
    container_name: ollama_cat
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - 11434
#    environment:
#      - gpus=all
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]